### ISSUE TITLE
TypeError: object() takes no parameters in middleware.py

### ISSUE THREAD

**Issue by mapeveri** [angvp/django-changuito#21]

**Comment by mapeveri** [comment]
See pull request #22 

Is it possible to release a new version?

Thanks!

**Comment by angvp** [comment]
I will do a release in a couple of hours, thanks!

**Comment by mapeveri** [comment]
Thanks my friend :)

**Comment by mapeveri** [comment]
@angvp Some news from the new release?. I need it for a project in production. Thank you so much.

**Comment by angvp** [comment]
1.1 uploaded thanks @mapeveri and sorry for the delay

**Comment by mapeveri** [comment]
Thank you so much :)

**Comment by angvp** [comment]
Updated to 1.2! sorry, but 1.1 didn't work for versions prior to 1.10, now it's fixed as well for old versions :)
